## Convolutional 1-Dim

This is a tutorial focusing on one single function *Conv1D* function from *tensorflow* library.

In [1]:
import tensorflow as tf

In [91]:
input_shape = (2,20,2)

In [92]:
x = tf.random.normal(input_shape)

In [101]:
x.shape

TensorShape([2, 20, 2])

In [102]:
x

<tf.Tensor: shape=(2, 20, 2), dtype=float32, numpy=
array([[[ 7.9686010e-01, -6.6684312e-01],
        [ 5.5639797e-01,  2.3833774e-01],
        [ 2.5320266e-04, -8.9196968e-01],
        [ 6.6768730e-01,  6.4210790e-01],
        [ 4.6035065e-03, -1.4953646e-01],
        [-5.7442617e-01,  3.3971784e-01],
        [-3.2520407e-01, -4.1204163e-01],
        [ 3.4481227e-01,  3.5877794e-01],
        [ 4.3358383e-01, -1.6852709e+00],
        [ 2.4002783e+00, -2.4830991e-01],
        [-1.2335764e+00,  6.3860804e-01],
        [-6.6572785e-01,  1.9594632e+00],
        [-2.2027427e-01,  5.3523064e-01],
        [-9.9526078e-01,  5.2371186e-01],
        [-1.2952344e+00, -2.9586545e-01],
        [-6.7008924e-01, -5.8331585e-01],
        [ 3.0181477e+00,  1.7787707e+00],
        [ 6.0072505e-01,  1.2824241e+00],
        [ 1.2835287e+00,  3.2526663e-01],
        [-1.1155177e+00, -1.4145297e+00]],

       [[-1.0508752e+00, -3.6886171e-01],
        [-1.7271293e+00,  1.3413453e+00],
        [ 2.2199100e-0

In [112]:
y = tf.keras.layers.Conv1D(
    1, 2,
    activation='relu',
    input_shape=input_shape[1:])

In [113]:
y(x).shape

TensorShape([2, 19, 1])

In [114]:
y(x)

<tf.Tensor: shape=(2, 19, 1), dtype=float32, numpy=
array([[[0.21617515],
        [0.30163464],
        [0.        ],
        [0.70376617],
        [0.3267373 ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [2.6346264 ],
        [0.02729309],
        [0.32706016],
        [0.6173085 ],
        [0.        ],
        [0.        ],
        [0.        ],
        [3.0278938 ],
        [0.33676142],
        [1.3401303 ]],

       [[0.22742169],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.7422912 ],
        [0.        ],
        [2.819121  ],
        [0.        ],
        [0.96852237],
        [0.30876982],
        [0.        ],
        [0.23859017],
        [0.        ],
        [1.7774688 ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [1.4638245 ]]], dtype=float32)>