## Convolutional 1-Dim

This is a tutorial focusing on one single function *Conv1D* function from *tensorflow* library.

In [1]:
import tensorflow as tf

In [9]:
input_shape = (2,10,2)

In [10]:
x = tf.random.normal(input_shape)

In [11]:
x.shape

TensorShape([2, 10, 2])

In [12]:
x

<tf.Tensor: shape=(2, 10, 2), dtype=float32, numpy=
array([[[ 0.44321603, -0.8155655 ],
        [ 1.9522476 , -1.2845579 ],
        [-1.0337242 , -1.1547064 ],
        [-0.233404  , -0.15527269],
        [ 0.84556746, -0.23450328],
        [-0.85113657, -0.4523362 ],
        [-0.09221443,  0.12940037],
        [ 1.7347059 , -0.60228187],
        [ 0.8476888 ,  1.6970091 ],
        [ 0.78833777,  0.6827152 ]],

       [[-0.9048889 , -0.65631986],
        [ 1.7661815 ,  0.41865963],
        [ 3.0976613 ,  0.4515184 ],
        [ 0.67271906,  0.8146139 ],
        [-0.9284802 , -0.10714412],
        [-1.0257484 ,  0.74266243],
        [-0.5471226 ,  0.21737035],
        [ 0.5117721 , -1.1382924 ],
        [-0.36066863,  1.9841639 ],
        [ 0.49102724,  0.98558354]]], dtype=float32)>

In [13]:
y = tf.keras.layers.Conv1D(
    1, 2,
    activation='relu',
    input_shape=input_shape[1:])

In [14]:
y(x).shape

TensorShape([2, 9, 1])

In [15]:
y(x)

<tf.Tensor: shape=(2, 9, 1), dtype=float32, numpy=
array([[[2.714528  ],
        [0.        ],
        [0.63855404],
        [1.1192907 ],
        [0.        ],
        [0.33378226],
        [2.0633354 ],
        [0.        ],
        [0.        ]],

       [[2.1180353 ],
        [1.9767926 ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [1.299381  ],
        [0.        ],
        [0.        ]]], dtype=float32)>